spring:
  application:
    name: Userservice
    
server:
  port: 8080
  address: 0.0.0.0
  
  
  
oracle:
 datasource:
  jdbcUrl: ${db.dev.url}
  username: ${db.dev.username}
  password: ${db.dev.password}
  driver-class-name: oracle.jdbc.OracleDriver